# Site settings
title: Blog 1.0
header-img: img/home-bg.jpg
email: your-email@yourdomain.com
copyright_name: Tomasz Jama
description: "Personal blog of Tomasz Jama - software, hardware and some other random stuff"
baseurl: ""
url: "http://yourdomain.com"
github_username:  GvS666
email_username:  your-email@yourdomain.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
